## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'redpitaya'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_redpitaya become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/Belondra/pymodaq_plugins_redpitaya'
description = 'Plugin permettant l aquisition et l affichage des données d un spectromètre'

author = 'Bélondrade Matthieu, Dulong Antoine'
author-email = 'matthieu.belondrade@free.fr , antoine.dulong1@gmail.com'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pyvisa', 'pyvisa-py']
